{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "DrinkMaster V1 API docs",
    "description": "API documentation for Team project 'DrinkMaster' team 4. [Backend github repository](https://github.com/Illya-Bilyk/nodejs-teamproject-rest-api) | [Privacy Policy](https://...)",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "https://drinks-whm4.onrender.com" }],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Users",
      "description": "User endpoints"
    },
    {
      "name": "Filters",
      "description": "Filters endpoints"
    },
    {
      "name": "Drinks",
      "description": "Drinks endpoints"
    }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/auth/signin": {
      "post": {
        "tags": ["Auth"],
        "summary": "User authentication",
        "parameters": [],
        "requestBody": {
          "description": "Authentication's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized / Email or password is wrong",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/auth/signout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": {}
          },
          "400": {
            "description": "No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "tags": ["Auth"],
        "summary": "Get new pair of tokens (use Bearer {refreshToken} instead of accessToken)",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Object with session's id",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokensRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefreshTokensResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["Users"],
        "summary": "Get user info",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Users object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GetUserInfoRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserInfoResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body) / No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Users not found / Invalid user / Invalid session",
            "content": {}
          }
        }
      }
    },
    "/users/update": {
      "patch": {
        "tags": ["Users"],
        "summary": "Update user info",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Users object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GetUserInfoRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserInfoResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body) / No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Users not found / Invalid user / Invalid session",
            "content": {}
          }
        }
      }
    },
    "/users/subscribe": {
      "post": {
        "tags": ["Users"],
        "summary": "Subscribe to newsletters",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Users object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GetUserInfoRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserInfoResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body) / No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Users not found / Invalid user / Invalid session",
            "content": {}
          }
        }
      }
    },
    "/filters/categories": {
      "get": {
        "tags": ["Filters"],
        "summary": "Get a list of drink categories",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetCategoriesResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body) / No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Users not found / Invalid user / Invalid session",
            "content": {}
          }
        }
      }
    },
    "/filters/ingredients": {
      "get": {
        "tags": ["Filters"],
        "summary": "Get a list of drink ingredients",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetIngredientsResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body) / No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Users not found / Invalid user / Invalid session",
            "content": {}
          }
        }
      }
    },
    "/filters/glasses": {
      "get": {
        "tags": ["Filters"],
        "summary": "Get a list of drink containers",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetGlassesResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body) / No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Users not found / Invalid user / Invalid session",
            "content": {}
          }
        }
      }
    },
    "/drinks/mainpage": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Getting cocktails for the main page",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Users object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GetUserInfoRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserInfoResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body) / No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Users not found / Invalid user / Invalid session",
            "content": {}
          }
        }
      }
    },
    "/drinks/popular": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Getting popular cocktails",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Users object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GetUserInfoRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserInfoResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body) / No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Users not found / Invalid user / Invalid session",
            "content": {}
          }
        }
      }
    },
    "/drinks/search": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Getting cocktails by category + ingredient + keyword",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "required": "true",
            "default": "1",
            "description": "Current page for pagination"
          },
          {
            "in": "query",
            "name": "limit",
            "type": "string",
            "required": "true",
            "default": "9",
            "description": "Number of drinks per page"
          },
          {
            "in": "query",
            "name": "keyword",
            "type": "string",
            "required": "true",
            "default": "Ir",
            "description": "A word from the search bar - Enter the text ..."
          },
          {
            "in": "query",
            "name": "category",
            "type": "string",
            "required": "true",
            "default": "Coffee / Tea",
            "description": "A category from the category drop-down list, or an empty string"
          },
          {
            "in": "query",
            "name": "ingredient",
            "type": "string",
            "required": "true",
            "default": "Sugar",
            "description": "Ingredients from the ingredient drop-down list or an empty string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetSearchResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session / Users not found (invalid query) / Search query not found (invalid query)",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/drinks/own/add/img": {
      "post": {
        "tags": ["Drinks"],
        "summary": "Adding your image to your own cocktail",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Users files",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "cocktail": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddDrinkImgResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided / Bad request / File is missing",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/drinks/own/add": {
      "post": {
        "tags": ["Drinks"],
        "summary": "Adding your own cocktail",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Users object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddDrinkRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddDrinkResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided / Bad request",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session / Add request not made (invalid request)",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/drinks/own/remove/{drinkId}": {
      "delete": {
        "tags": ["Drinks"],
        "summary": "Deleting your own cocktail",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "drinkId",
            "type": "string",
            "required": "true",
            "default": "639b6de9ff77d221f190c51e",
            "description": "ID the selected drink"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RemoveDrinkResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided / Bad request / {drinkId} is not valid id",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/drinks/own": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Getting your own cocktails",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "required": "true",
            "default": "1",
            "description": "Current page for pagination"
          },
          {
            "in": "query",
            "name": "limit",
            "type": "string",
            "required": "true",
            "default": "9",
            "description": "Number of drinks per page"
          }
        ],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetDrinkResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided / Bad request / {drinkId} is not valid id",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/drinks/favorite/add/{drinkId}": {
      "post": {
        "tags": ["Drinks"],
        "summary": "Adding a cocktail to favorites",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "drinkId",
            "type": "string",
            "required": "true",
            "default": "639b6de9ff77d221f190c51e",
            "description": "ID the selected drink"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddFavoriteResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided / Bad request / {drinkId} is not valid id",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session ",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/drinks/favorite/remove/{drinkId}": {
      "delete": {
        "tags": ["Drinks"],
        "summary": "Removing a cocktail from favorites",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "drinkId",
            "type": "string",
            "required": "true",
            "default": "639b6de9ff77d221f190c51e",
            "description": "ID the selected drink"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddFavoriteResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided / Bad request / {drinkId} is not valid id",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session ",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/drinks/favorite": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Receiving cocktails from the chosen ones",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "required": "true",
            "default": "1",
            "description": "Current page for pagination"
          },
          {
            "in": "query",
            "name": "limit",
            "type": "string",
            "required": "true",
            "default": "9",
            "description": "Number of drinks per page"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetFavoriteResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided / Bad request ",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session / Users not found (invalid query) / Favorites drink not found ",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/drinks/{drinkId}": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Get one cocktail per ID",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "drinkId",
            "type": "string",
            "required": "true",
            "default": "639b6de9ff77d221f190c521",
            "description": "ID the selected drink"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetByIDResponse"
                }
              }
            }
          },
          "400": {
            "description": "No token provided",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Not found / Invalid user / Invalid session / Drink not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "required": ["name", "birthday", "email", "password"],
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "minLength": 2,
            "maxLength": 100,
            "example": "John"
          },
          "birthday": {
            "type": "string",
            "description": "User's birthday",
            "minLength": 10,
            "maxLength": 10,
            "example": "01/01/2001"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "minLength": 3,
            "maxLength": 254
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "Qwerty?12",
            "minLength": 8,
            "maxLength": 100
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "accessToken": {
            "type": "string",
            "description": "Session's access token (needed for all requests)",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZmMyMDg1YmQwOTM2NTI4MTA3Y2UyNzQiLCJzaWQiOiI1ZmMyZDJmY2UxZDIwNTA2NzAyYmRkMjIiLCJpYXQiOjE2MDY2MDM1MTYsImV4cCI6MTYwNjYwNzExNn0.rJ_QjU4KvA76H96RHsvOBChK0Vjbd0NmqjMxdQVJIXA"
          },
          "sid": {
            "type": "string",
            "description": "Session's id (needed for /auth/refresh)",
            "example": "65423c61f2c5a9d94a44c85c"
          },
          "user": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User name",
                "example": "John"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "birthday": {
                "type": "string",
                "description": "User's birthday",
                "example": "01/01/2001"
              }
            }
          }
        }
      },
      "LoginRequest": {
        "required": ["email", "password"],
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "minLength": 3,
            "maxLength": 254
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "minLength": 8,
            "maxLength": 100,
            "example": "Qwerty?12"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "accessToken": {
            "type": "string",
            "description": "Session's access token (needed for all requests)",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZmMyMDg1YmQwOTM2NTI4MTA3Y2UyNzQiLCJzaWQiOiI1ZmMyZDJmY2UxZDIwNTA2NzAyYmRkMjIiLCJpYXQiOjE2MDY2MDM1MTYsImV4cCI6MTYwNjYwNzExNn0.rJ_QjU4KvA76H96RHsvOBChK0Vjbd0NmqjMxdQVJIXA"
          },
          "refreshToken": {
            "type": "string",
            "description": "Session's refresh token (needed for /auth/refresh)",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZmMyMDg1YmQwOTM2NTI4MTA3Y2UyNzQiLCJzaWQiOiI1ZmMyZDJmY2UxZDIwNTA2NzAyYmRkMjIiLCJpYXQiOjE2MDY2MDM1MTYsImV4cCI6MTYwNjYwNzExNn0.rJ_QjU4KvA76H96RHsvOBChK0Vjbd0NmqjMxdQVJIXB"
          },
          "sid": {
            "type": "string",
            "description": "Session's id (needed for /auth/refresh)",
            "example": "507f1f77bcf86cd799439011"
          },
          "user": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User name",
                "example": "John"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "birthday": {
                "type": "string",
                "description": "User's birthday",
                "example": "01/01/2001"
              }
            }
          }
        }
      },
      "RefreshTokensRequest": {
        "type": "object",
        "properties": {
          "sid": {
            "type": "string",
            "description": "Session's ('sid' field after authentication)",
            "example": "507f1f77bcf86cd799439011"
          }
        }
      },
      "RefreshTokensResponse": {
        "type": "object",
        "properties": {
          "newAccessToken": {
            "type": "string",
            "description": "Access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZmMyMDg1YmQwOTM2NTI4MTA3Y2UyNzQiLCJzaWQiOiI1ZmMyZDJmY2UxZDIwNTA2NzAyYmRkMjIiLCJpYXQiOjE2MDY2MDM1MTYsImV4cCI6MTYwNjYwNzExNn0.rJ_QjU4KvA76H96RHsvOBChK0Vjbd0NmqjMxdQVJIXA"
          },
          "newRefreshToken": {
            "type": "string",
            "description": "Refresh token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZmMyMDg1YmQwOTM2NTI4MTA3Y2UyNzQiLCJzaWQiOiI1ZmMyZDJmY2UxZDIwNTA2NzAyYmRkMjIiLCJpYXQiOjE2MDY2MDM1MTYsImV4cCI6MTYwNjYwNzExNn0.rJ_QjU4KvA76H96RHsvOBChK0Vjbd0NmqjMxdQVJIXB"
          },
          "newSid": {
            "type": "string",
            "description": "New session's id",
            "example": "507f1f77bcf86cd799439011"
          }
        }
      },
      "GetUserInfoRequest": {},
      "GetUserInfoResponse": {},
      "GetSearchResponse": {
        "type": "object",
        "properties": {
          "page": {
            "type": "string",
            "description": "Current page for pagination",
            "example": "1"
          },
          "per_page": {
            "type": "string",
            "description": "Number of drinks per page",
            "example": "9"
          },
          "max_page": {
            "type": "string",
            "description": "The number of drinks in the database according to the query criteria",
            "example": "1"
          },
          "drinks": {
            "type": "array",
            "description": "The array of drinks in the database according to the query criteria",
            "example": [
              {
                "_id": "639b6de9ff77d221f190c508",
                "drink": "Irish Coffee",
                "drinkAlternate": "Sorry, not specified",
                "tags": "IBA,ContemporaryClassic",
                "video": "https://youtu.be/9xwtCHELxMA?si=j9qrBEoFTqqgPVCr",
                "category": "Coffee / Tea",
                "IBA": "Contemporary Classics",
                "alcoholic": "Alcoholic",
                "glass": "Irish coffee cup",
                "description": "Irish Coffee is a classic hot cocktail that combines the richness of coffee with the smoothness of Irish whiskey. It is made by pouring hot coffee into a glass, adding a shot of Irish whiskey, and topping it off with a dollop of whipped cream. The warmth of the drink and the sweetness of the cream make it a comforting and indulgent treat.",
                "instructions": "Heat the coffee, whiskey and sugar; do not boil. Pour into glass and top with cream; serve hot.",
                "instructionsES": "Calienta el café, el whisky y el azúcar; no hierva. Vierta en un vaso y cubra con crema; servir caliente.",
                "instructionsDE": "Kaffee, Whiskey und Zucker erhitzen; nicht kochen lassen. In ein Glas geben und mit Sahne übergießen; heiß servieren.",
                "instructionsFR": "Faire chauffer le café, le whisky et le sucre ; ne pas faire bouillir. Verser dans un verre et garnir de crème; Servir chaud.",
                "instructionsIT": "Riscaldare il caffè, il whisky e lo zucchero; non bollire. Versare nel bicchiere e ricoprire con la panna; servito caldo.",
                "instructionsRU": "Нагрейте кофе, виски и сахар; не кипятить. Перелейте в стакан и украсьте сливками; подавать горячим.",
                "instructionsPL": "Podgrzej kawę, whisky i cukier; nie gotuj. Wlać do szklanki i posypać śmietaną; podawać na gorąco.",
                "instructionsUK": "Розігріти каву, віскі і цукор; не кип'ятити. Перелити в келих і зверху полити кремом; подавати гарячим.",
                "drinkThumb": "https://ftp.goit.study/img/drinkify/recipes/Irish_Coffee.jpg",
                "ingredients": [
                  {
                    "_id": "653e4aacf694b8bfbdce6d78",
                    "title": "Irish whiskey",
                    "measure": "1 1/2 oz ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4c2"
                  },
                  {
                    "_id": "653e4aacf694b8bfbdce6d79",
                    "title": "Coffee",
                    "measure": "8 oz ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4e7"
                  },
                  {
                    "_id": "653e4aacf694b8bfbdce6d7a",
                    "title": "Sugar",
                    "measure": "1 tsp ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4bc"
                  },
                  {
                    "_id": "653e4aacf694b8bfbdce6d7b",
                    "title": "Whipped cream",
                    "measure": "1 tblsp ",
                    "ingredientId": "64f1d5c069d8333cf130fb38"
                  }
                ],
                "shortDescription": "A classic hot cocktail with coffee, Irish whiskey, and whipped cream."
              }
            ]
          }
        }
      },
      "AddDrinkImgResponse": {
        "type": "object",
        "properties": {
          "avatarURL": {
            "type": "string",
            "description": "Current page for pagination",
            "example": "https://res.cloudinary.com/dl1cncruu/image/upload/v1698760293/cocktails/653fa858149cd42514905850-2EmQibRWanpjmcqFMIbOK.jpg"
          }
        }
      },
      "AddDrinkRequest": {
        "required": [
          "drink",
          "category",
          "alcoholic",
          "glass",
          "description",
          "instructions",
          "drinkThumb",
          "ingredients"
        ],
        "type": "object",
        "properties": {
          "drink": {
            "type": "string",
            "description": "Drink's name",
            "minLength": 2,
            "maxLength": 100,
            "example": "Strong"
          },
          "category": {
            "type": "string",
            "description": "Drink's category",
            "minLength": 2,
            "maxLength": 100,
            "example": "Ordinary Drink"
          },
          "alcoholic": {
            "type": "string",
            "description": "The presence of alcohol",
            "enum": ["Alcoholic", "Non alcoholic"]
          },
          "glass": {
            "type": "string",
            "description": "User's password",
            "example": "A glass of drink",
            "minLength": 2,
            "maxLength": 150
          },
          "description": {
            "type": "string",
            "description": "Drink's description",
            "minLength": 2,
            "maxLength": 500,
            "example": "Strong is a refreshing cocktail that combines the flavors of citrus and mint. It is made with fresh lime juice, orange liqueur, and a touch of mint syrup. The drink is served over ice and garnished with a sprig of mint. It is the perfect beverage for a hot summer day."
          },
          "instructions": {
            "type": "string",
            "description": "Drink's instructions",
            "minLength": 2,
            "maxLength": 500,
            "example": "In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well. Strain into a cocktail glass and garnish with the nutmeg."
          },
          "drinkThumb": {
            "type": "string",
            "description": "Drink's image",
            "minLength": 2,
            "maxLength": 500,
            "example": "https://res.cloudinary.com/dl1cncruu/image/upload/v1698926456/cocktails/65436e6f6db048cb734906eb-gpfjfDjaEjdaKVzX06itZ.jpg"
          },
          "ingredients": {
            "type": "array",
            "description": "Array of ingredients",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "Drink's ingredients title",
                  "minLength": 2,
                  "maxLength": 100,
                  "example": "Club soda"
                },
                "measure": {
                  "type": "string",
                  "description": "Drink's ingredients measure",
                  "minLength": 2,
                  "maxLength": 100,
                  "example": "1 1/2 oz"
                }
              }
            }
          }
        }
      },
      "AddDrinkResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "drink added"
          }
        }
      },
      "RemoveDrinkResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "drink deleted"
          }
        }
      },
      "GetDrinkResponse": {
        "type": "object",
        "properties": {
          "drink": {
            "type": "string",
            "description": "Drink's name",
            "example": "Summer apple"
          },
          "category": {
            "type": "string",
            "description": "Drink's category",
            "example": "Ordinary Drink"
          },
          "alcoholic": {
            "type": "string",
            "description": "The presence of alcohol",
            "example": "Alcoholic"
          },
          "glass": {
            "type": "string",
            "description": "A glass of drink",
            "example": "Cocktail glass"
          },
          "description": {
            "type": "string",
            "description": "Drink's description",
            "example": "Quentin is a refreshing cocktail that combines the flavors of citrus a…"
          },
          "instructions": {
            "type": "string",
            "description": "Drink's instructions",
            "example": "In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well. Strain into a cocktail glass and garnish with the nutmeg."
          },
          "drinkThumb": {
            "type": "string",
            "description": "Drink's image",
            "example": "https://res.cloudinary.com/dl1cncruu/image/upload/v1698918620/cocktails/65436e6f6db048cb734906eb-wzK6R4B5iNNi8JvAAwu1R.jpg"
          },
          "ingredients": {
            "type": "array",
            "description": "Array of ingredients",
            "example": [
              {
                "title": {
                  "type": "string",
                  "description": "Drink's ingredients title",
                  "example": "Dark rum"
                },
                "measure": {
                  "type": "string",
                  "description": "Drink's ingredients measure",
                  "example": "1 1/2 oz"
                },
                "_id": {
                  "type": "string",
                  "description": "Ingredients ID",
                  "example": "65424135aced313723e9186a"
                }
              },
              {
                "title": {
                  "type": "string",
                  "description": "Drink's ingredients title",
                  "example": "Kahlua"
                },
                "measure": {
                  "type": "string",
                  "description": "Drink's ingredients measure",
                  "example": "1/2 oz"
                },
                "_id": {
                  "type": "string",
                  "description": "Ingredients ID",
                  "example": "65424135aced313723e9186b"
                }
              },
              {
                "title": {
                  "type": "string",
                  "description": "Drink's ingredients title",
                  "example": "Light cream"
                },
                "measure": {
                  "type": "string",
                  "description": "Drink's ingredients measure",
                  "example": "1 oz"
                },
                "_id": {
                  "type": "string",
                  "description": "Ingredients ID",
                  "example": "65424135aced313723e9186c"
                }
              },
              {
                "title": {
                  "type": "string",
                  "description": "Drink's ingredients title",
                  "example": "Nutmeg"
                },
                "measure": {
                  "type": "string",
                  "description": "Drink's ingredients measure",
                  "example": "1/8 tsp grated"
                },
                "_id": {
                  "type": "string",
                  "description": "Ingredients ID",
                  "example": "65424135aced313723e9186d"
                }
              }
            ]
          },
          "shortDescription": {
            "type": "string",
            "description": "Drink's short description",
            "example": "A refreshing and citrusy cocktail with a hint of mint."
          },
          "owner": {
            "type": "string",
            "description": "Owner's ID",
            "example": "6543c84e61d98501f9f42ff3"
          },
          "createdAt": {
            "type": "string",
            "description": "Data created",
            "example": "2023-11-01T12:14:45.965Z"
          },
          "updatedAt": {
            "type": "string",
            "description": "Data last updated",
            "example": "2023-11-01T12:14:45.965Z"
          }
        }
      },
      "AddFavoriteResponse": {
        "type": "object",
        "properties": {
          "favoriteDrinks": {
            "type": "string",
            "description": "Number of favorite drinks",
            "example": "1"
          }
        }
      },
      "DeleteFavoriteResponse": {
        "type": "object",
        "properties": {
          "favoriteDrinks": {
            "type": "string",
            "description": "Number of favorite drinks",
            "example": "1"
          }
        }
      },
      "GetFavoriteResponse": {
        "type": "object",
        "properties": {
          "page": {
            "type": "string",
            "description": "Current page for pagination",
            "example": "1"
          },
          "per_page": {
            "type": "string",
            "description": "Number of drinks per page",
            "example": "9"
          },
          "max_page": {
            "type": "string",
            "description": "The number of drinks in the database according to the query criteria",
            "example": "1"
          },
          "drinks": {
            "type": "array",
            "description": "The array of drinks in the database according to the query criteria",
            "example": [
              {
                "_id": "639b6de9ff77d221f190c508",
                "drink": "Irish Coffee",
                "drinkAlternate": "Sorry, not specified",
                "tags": "IBA,ContemporaryClassic",
                "video": "https://youtu.be/9xwtCHELxMA?si=j9qrBEoFTqqgPVCr",
                "category": "Coffee / Tea",
                "IBA": "Contemporary Classics",
                "alcoholic": "Alcoholic",
                "glass": "Irish coffee cup",
                "description": "Irish Coffee is a classic hot cocktail that combines the richness of coffee with the smoothness of Irish whiskey. It is made by pouring hot coffee into a glass, adding a shot of Irish whiskey, and topping it off with a dollop of whipped cream. The warmth of the drink and the sweetness of the cream make it a comforting and indulgent treat.",
                "instructions": "Heat the coffee, whiskey and sugar; do not boil. Pour into glass and top with cream; serve hot.",
                "instructionsES": "Calienta el café, el whisky y el azúcar; no hierva. Vierta en un vaso y cubra con crema; servir caliente.",
                "instructionsDE": "Kaffee, Whiskey und Zucker erhitzen; nicht kochen lassen. In ein Glas geben und mit Sahne übergießen; heiß servieren.",
                "instructionsFR": "Faire chauffer le café, le whisky et le sucre ; ne pas faire bouillir. Verser dans un verre et garnir de crème; Servir chaud.",
                "instructionsIT": "Riscaldare il caffè, il whisky e lo zucchero; non bollire. Versare nel bicchiere e ricoprire con la panna; servito caldo.",
                "instructionsRU": "Нагрейте кофе, виски и сахар; не кипятить. Перелейте в стакан и украсьте сливками; подавать горячим.",
                "instructionsPL": "Podgrzej kawę, whisky i cukier; nie gotuj. Wlać do szklanki i posypać śmietaną; podawać na gorąco.",
                "instructionsUK": "Розігріти каву, віскі і цукор; не кип'ятити. Перелити в келих і зверху полити кремом; подавати гарячим.",
                "drinkThumb": "https://ftp.goit.study/img/drinkify/recipes/Irish_Coffee.jpg",
                "ingredients": [
                  {
                    "_id": "653e4aacf694b8bfbdce6d78",
                    "title": "Irish whiskey",
                    "measure": "1 1/2 oz ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4c2"
                  },
                  {
                    "_id": "653e4aacf694b8bfbdce6d79",
                    "title": "Coffee",
                    "measure": "8 oz ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4e7"
                  },
                  {
                    "_id": "653e4aacf694b8bfbdce6d7a",
                    "title": "Sugar",
                    "measure": "1 tsp ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4bc"
                  },
                  {
                    "_id": "653e4aacf694b8bfbdce6d7b",
                    "title": "Whipped cream",
                    "measure": "1 tblsp ",
                    "ingredientId": "64f1d5c069d8333cf130fb38"
                  }
                ],
                "shortDescription": "A classic hot cocktail with coffee, Irish whiskey, and whipped cream."
              }
            ]
          }
        }
      },
      "GetByIDResponse": {
        "type": "object",
        "example": [
          {
            "users": [],
            "_id": "639b6de9ff77d221f190c521",
            "drink": "Abilene",
            "drinkAlternate": "Sorry, not specified",
            "tags": "Sorry, not specified",
            "video": "Sorry, not specified",
            "category": "Ordinary Drink",
            "IBA": "Sorry, not specified",
            "alcoholic": "Alcoholic",
            "glass": "Highball glass",
            "description": "Abilene is a whiskey-based cocktail that offers a delightful balance of sweet and sour flavors. This classic drink combines whiskey, vermouth, and a touch of sweet grenadine, resulting in a sophisticated and well-rounded beverage. Sip on an Abilene cocktail and let the smooth whiskey and subtle sweetness transport you to a cozy lounge.",
            "instructions": "Pour all of the ingredients into a highball glass almost filled with ice cubes. Stir well.",
            "instructionsES": "Coloque todos los ingredientes en un vaso alto casi lleno de cubitos de hielo. Sacudir bien.",
            "instructionsDE": "Alle Zutaten in ein fast mit Eiswürfeln gefülltes Longdrinkglas geben. Gut umrühren.",
            "instructionsFR": "Verser tous les ingrédients dans un verre highball presque rempli de glaçons. Bien mélanger.",
            "instructionsIT": "Versare tutti gli ingredienti in un bicchiere highball riempito di cubetti di ghiaccio. Mescolare bene.",
            "instructionsRU": "Налейте все ингредиенты в хайболл, почти наполненный кубиками льда. Размешайте как следует.",
            "instructionsPL": "Wlej wszystkie składniki do szklanki typu highball prawie wypełnionej kostkami lodu. Dobrze wymieszać.",
            "instructionsUK": "Перелийте всі інгредієнти в стакан хайбол, майже наповнений кубиками льоду. Добре розмішати.",
            "drinkThumb": "https://ftp.goit.study/img/drinkify/recipes/Abilene.jpg",
            "ingredients": [
              {
                "_id": "654798be02738307339ac0e3",
                "title": "Dark rum",
                "measure": "1 1/2 oz ",
                "ingredientId": "64aebb7f82d96cc69e0eb4a7",
                "ingredientThumb": "https://ftp.goit.study/img/drinkify/ingredients/Dark_rum.png"
              },
              {
                "_id": "654798be02738307339ac0e4",
                "title": "Peach nectar",
                "measure": "2 oz ",
                "ingredientId": "64aebb7f82d96cc69e0eb4f5",
                "ingredientThumb": "https://ftp.goit.study/img/drinkify/ingredients/Peach_nectar.png"
              },
              {
                "_id": "654798be02738307339ac0e5",
                "title": "Orange juice",
                "measure": "3 oz ",
                "ingredientId": "64f1d5c069d8333cf130fb3d",
                "ingredientThumb": "https://ftp.goit.study/img/drinkify/ingredients/"
              }
            ],
            "shortDescription": "A whiskey-based cocktail with a blend of sweet and sour flavors.",
            "favorite": false
          }
        ]
      },
      "GetCategoriesResponse": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Category name"
        },
        "example": [
          "Beer",
          "Cocktail",
          "Cocoa",
          "Coffee / Tea",
          "Homemade Liqueur",
          "Ordinary Drink",
          "Other/Unknown",
          "Punch / Party Drink",
          "Shake",
          "Shot",
          "Soft Drink"
        ]
      },
      "GetIngredientsResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Ingredient ID number",
              "example": "64aebb7f82d96cc69e0eb4c9"
            },
            "title": {
              "type": "string",
              "description": "Ingredient title",
              "example": "Coffee brandy"
            },
            "ingredientThumb": {
              "type": "string",
              "description": "Ingredient image link",
              "example": "https://ftp.goit.study/img/drinkify/ingredients/Coffee_brandy.png"
            },
            "thumb-medium": {
              "type": "string",
              "description": "Ingredient medium image link",
              "example": "https://ftp.goit.study/img/drinkify/ingredients/Coffee_brandy-Medium.png"
            },
            "thumb-small": {
              "type": "string",
              "description": "Ingredient small image link",
              "example": "https://ftp.goit.study/img/drinkify/ingredients/Coffee_brandy-Small.png"
            },
            "alcohol": {
              "type": "string",
              "description": "Content of alcohol",
              "example": "Yes"
            }
          }
        }
      },
      "GetGlassesResponse": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Glass name"
        },
        "example": [
          "Balloon Glass",
          "Beer Glass",
          "Beer mug",
          "Beer pilsner",
          "Brandy snifter",
          "Champagne Flute",
          "Champagne flute",
          "Cocktail Glass",
          "Cocktail glass",
          "Coffee Mug",
          "Coffee mug",
          "Collins Glass",
          "Collins glass",
          "Copper Mug",
          "Cordial glass",
          "Coupe Glass",
          "Highball Glass",
          "Highball glass",
          "Hurricane glass",
          "Irish coffee cup",
          "Jar",
          "Margarita glass",
          "Margarita/Coupette glass",
          "Martini Glass",
          "Mason jar",
          "Nick and Nora Glass",
          "Old-Fashioned glass",
          "Old-fashioned glass",
          "Pint glass",
          "Pitcher",
          "Pousse cafe glass",
          "Punch Bowl",
          "Punch bowl",
          "Shot Glass",
          "Shot glass",
          "Whiskey Glass",
          "Whiskey sour glass",
          "White wine glass",
          "Wine Glass"
        ]
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
